name: Build and Push Docker Springboot Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          
      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install

      - name: Install Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Buildx
        run: |
          docker buildx version

      - name: Print $USER
        run: echo "The value of \$USER is $USER"

      - name: Add GitHub Actions runner user to the docker group
        run: sudo usermod -aG docker ${{ github.actor }}
        
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767398147229.dkr.ecr.us-east-1.amazonaws.com
          sudo docker buildx build -t my-app:latest .
          sudo docker tag my-app:latest 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest
          sudo docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Build Docker image
      #   run: |
      #     sudo docker buildx build -t springboot-github-workflow-deployment:latest .
      #     docker images
      #   working-directory: .

          
      # - name: Tag Docker image
      #   run: |
      #     sudo docker tag springboot-github-workflow-deployment:latest 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest
      #   working-directory: .

      # - name: Push Docker image to ECR
      #   run: |
      #     sudo docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest