name: Build and Push Docker Springboot Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      
      - name: Install Maven
        run: |
          sudo apt-get install -y maven
          
      - name: Install Maven
        run: mvn clean install

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Print $USER
        run: echo "The value of \$USER is $USER"

      - name: Add GitHub Actions runner user to the docker group
        run: sudo usermod -aG docker ${{ github.actor }}
        
      - name: Build and push Docker image to Amazon ECR Public
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767398147229.dkr.ecr.us-east-1.amazonaws.com         
          docker build -t gitworkflowrepo .
          docker tag gitworkflowrepo:latest 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:latest
          docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
