name: Build and Push Docker Springboot Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          
      - name: Install Maven
        run: mvn clean install

      - name: Install Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Buildx
        run: |
          docker buildx create --name mynewappbuilder6
          docker buildx use mynewappbuilder6
          docker buildx inspect --bootstrap

      - name: Print $USER
        run: echo "The value of \$USER is $USER"

      - name: Add GitHub Actions runner user to the docker group
        run: sudo usermod -aG docker ${{ github.actor }}
        
      - name: Build and push Docker image to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y6y7n3n4
          docker buildx build --platform linux/amd64 -t myapp1:latest --push .
          docker tag myapp1:latest public.ecr.aws/y6y7n3n4/myapp1:latest
          docker push public.ecr.aws/y6y7n3n4/myapp1:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
