name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:   
  deploy:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install eksctl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Amazon EKS cluster
        run: |
          eksctl create cluster --name springboot-github-workflow --version 1.28 --nodes=1 --node-type=t2.small --region us-east-1

      - name: Configure kubectl for Amazon EKS cluster
        run: aws eks --region us-east-1 update-kubeconfig --name springboot-github-workflow

      - name: Deploy pod
        run: kubectl apply -f ./k8s.yaml --validate=false

      # - name: Expose pod as service
      #   run: kubectl expose pod springboot-github-workflow-deployment --port=80 --target-port=8080 --type=LoadBalancer
        
