name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767398147229.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Build Docker image
        run: |
          docker build -t springboot-github-workflow-deployment .
        working-directory: .

      - name: Tag Docker image
        run: |
          docker tag springboot-github-workflow-deployment:latest 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest
        working-directory: .

      - name: Push Docker image to ECR
        run: |
          docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/springboot-github-workflow-deployment:latest
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Amazon EKS cluster
        run: |
          eksctl create cluster --name spring-boot-21-linux --version 1.28 --nodes=1 --node-type=t2.small --region us-east-1

      - name: Configure kubectl for Amazon EKS cluster
        run: aws eks --region us-east-1 update-kubeconfig --name spring-boot-21-linux

      - name: Deploy pod
        run: kubectl apply -f ../k8s.yaml

      - name: Expose pod as service
        run: kubectl expose pod springboot-github-workflow-deployment --port=80 --target-port=8080 --type=LoadBalancer
        