name: Build and Push Docker Springboot Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      
      # - name: Install Maven
      #   run: |
      #     sudo apt-get install -y maven
          
      - name: Build the Maven project
        run: mvn package

      - name: Set IMAGE_TAG
        id: set_image_tag
        run: echo "::set-output name=IMAGE_TAG::$(date +%Y%m%d%H%M%S)"


      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo systemctl start docker
      #     sudo systemctl enable docker

      - name: Build and push Docker image to Amazon ECR
        id: build_and_push_image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IMAGE_TAG: ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767398147229.dkr.ecr.us-east-1.amazonaws.com 
          sudo docker build -t gitworkflowrepo:${IMAGE_TAG} .
          sudo docker tag gitworkflowrepo:${IMAGE_TAG} 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:${IMAGE_TAG}
          sudo docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:${IMAGE_TAG}

        
      - name: Build and push Docker image to Amazon ECR Public
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767398147229.dkr.ecr.us-east-1.amazonaws.com         
          docker build -t gitworkflowrepo .
          docker tag gitworkflowrepo:latest 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:latest
          docker push 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
