name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Amazon EKS cluster
        run: |
          eksctl create cluster --name springboot-github-workflow --version 1.28 --nodes=1 --node-type=t2.small --region us-east-1

      - name: Configure kubectl for Amazon EKS cluster
        run: aws eks --region us-east-1 update-kubeconfig --name springboot-github-workflow

      - name: Deploy pod
        run: kubectl apply -f ./k8s.yaml --validate=false

      # - name: Expose pod as service
      #   run: kubectl expose pod springboot-github-workflow-deployment --port=80 --target-port=8080 --type=LoadBalancer
        
